"""empty message

Revision ID: bb5f13879887
Revises: a8a738a8de1e
Create Date: 2020-06-02 17:00:30.345846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5f13879887'
down_revision = 'a8a738a8de1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweet', 'text',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.add_column('user', sa.Column('username', sa.String(length=250), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('user', 'username')
    op.alter_column('tweet', 'text',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
